/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import org.junit.Test;
import static org.junit.Assert.*;
import com.revature.exceptions.UsernameOrPasswordIncorrectException;

public class UserTesting {

    @Mock
    static IUserDao ud;

    @InjectMocks
    static UserService us;

    @Test
    public void checkCreatesNewUser(){

        when(ud.createUser(any())).thenReturn(new User(0, "JDoe", "password", "John", "Doe", "jdoe@mail.com"));
        us.registerUser("JDoe", "password", "John", "Doe", "jdoe@mail.com");
        verify(ud).createUser(any());

    }

    @Test
    public void checkLoginSuccess() throws UsernameOrPasswordIncorrectException {

        when(ud.readUserByUsername(any())).thenReturn(new User(0, "JDoe", "password", "John", "Doe", "jdoe@mail.com"));
        User loggin = us.loginUser("JDoe", "password");
        verify(ud).readUserByUsername(any());
        assertEquals("Username should be JDoe", "JDoe", loggin.getUsername());
    }

    @Test(expected=UsernameOrPasswordIncorrectException.class)
    public void wrongUsernameTest() throws UsernameOrPasswordIncorrectException{
        User u = null;
        when(ud.readUserByUsername(any())).thenReturn(u);

        User loggedIn = us.loginUser("JDoe", "password");
    }
}
