/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;


import com.revature.controllers.UserController;
import com.revature.dao.IUserDao;
import com.revature.dao.UserDaoJDBC;
import com.revature.services.UserService;
import io.javalin.Javalin;

import static io.javalin.apibuilder.ApiBuilder.*;

public class ReimbursementDriver {


    public static void main(String[] args) {

        IUserDao ud = new UserDaoJDBC();
        UserService us = new UserService(ud);
        UserController uc = new UserController(us);


        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.routes(()-> {
            path("users", () -> {
                post("/register", uc.handleRegister);
            });

        });

        server.start(8000);

    }
}
